import React from "react";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";
import { getSetsData } from "../../lib/sets";
import Head from "next/head";
import FlipCard from "../../components/FlipCard";

export async function getServerSideProps(context) {
  const set = await getSetsData(context.query.id);
  return {
    props: {
      set,
    }, // will be passed to the page component as props
  };
}
const SetId = (props) => {
  const { set } = props;
  const { fields } = set.items[0];
  const { platform, setName, year, cards } = fields;
  return (
    <section>
      <Head>
        <title>{platform} Set</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        <Grid item>
          <Typography variant={"h2"}>{platform}</Typography>
          <Typography variant={"h3"}>
            {setName}/{year}
          </Typography>
        </Grid>
      </Grid>
      <Grid container spacing={2}>
        {cards.map((card, idx) => {
          return (
            <Grid item key={`${card.name}-${idx}`}>
              <FlipCard images={card.fields.images} />
            </Grid>
          );
        })}
      </Grid>
    </section>
  );
};

export default SetId;
