import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import { getLeagueData } from "../lib/leagues";
import BottomNavigation from "../components/BottomNavigation";
import formatLeagueData from "../utils/formatLeagueData";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemText from "@mui/material/ListItemText";
import Avatar from "@mui/material/Avatar";
import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";

export async function getStaticProps() {
  const league = await getLeagueData();
  console.log("league", league);
  return {
    props: {
      league,
    },
  };
}

export default function Home(props) {
  const { league } = props;
  const leagueData = formatLeagueData(league);
  return (
    <div className={styles.container}>
      <Head>
        <title>Sports NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container>
          <Grid item xs={12}>
            <Typography align={"center"} component={"h1"} variant={"h1"}>
              Welcome to Sports NFT!!
            </Typography>
          </Grid>
          <Grid item xs={12} align={"center"}>
            <Box sx={{ pb: 7 }}>
              <CssBaseline />
              {/*<List>*/}
              {/*  <ListItem button>*/}
              {/*    <ListItemAvatar>*/}
              {/*      <Avatar alt="Profile Picture" />*/}
              {/*    </ListItemAvatar>*/}
              {/*    <ListItemText primary={"hello"} secondary={"world"} />*/}
              {/*  </ListItem>*/}
              {/*</List>*/}
              <BottomNavigation data={leagueData} />
            </Box>
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
