import Head from "next/head";
import Image from "next/image";
import useSwr from "swr";
import styles from "../styles/Home.module.css";

const fetcher = (url) =>
  fetch(url)
    .then((res) => res.json())
    .catch((error) => error);

export default function Home(props) {
  const { data, error } = useSwr("/api/content/nft", fetcher);
  console.log(data);

  if (error) return <div>Failed to load users</div>;
  if (!data) return <div>Loading...</div>;

  const { players } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Sports NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>NFTs</h1>
        <p>Here are the list of NFTs</p>
        {players &&
          players.map((player, idx) => {
            return <div key={`${player}-${idx}`}>{player.athlete}</div>;
          })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
